config/routes.rb
Rails.application.routes.draw do
  root :to => 'occurrences#charts'
  get 'developer' => 'developer#index'
  post 'developer' => 'developer#index'
  get 'occurrences/charts' => 'occurrences#charts'
  get 'occurrences/maps' => 'occurrences#maps'
  post 'occurrences/maps' => 'occurrences#maps'
  get 'occurrences' => 'occurrences#index'
end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
  belongs_to :district
  belongs_to :crime_type  

  validates :crime_type_id, presence: true
  validates :year, presence: true
  validates :month, presence: true
  validates :value, presence: true
  validates :district_id, presence: true, uniqueness: {scope: [:crime_type_id, :year, :month]}

  def self.completed? district, year
    where('district_id = ?', district.id).where('year = ?', year).distinct.count(:month) == 12
  end

  def self.map_filter year, month, crime_type
    filter_year(year)
      .filter_month(month)
      .filter_crime_type(crime_type)
      .joins(district: :regions)
      .select("regions.name")
      .group("regions.name")
      .sum(:value)
  end

  def self.city_data crime, month, year
    filter_year(year).
      filter_month(month).
      filter_crime_type(crime).
      filter_district(District.get_city.id.to_s).
      group(:month).group(:year).order(:year).order(:month).sum(:value)
  end

  def self.optional_filter(*args)
    args.each do |arg|
      self.class_eval("scope :filter_#{arg}, ->(#{arg}) { (#{arg}.nil? or #{arg}.empty?)? (all): (where(#{arg}: #{arg})) }")
    end
  end  
  optional_filter :year, :month, :crime_type, :district
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  include UploadHelper
  include KmlHelper

  def index
  end

  def charts
    setup_dropdowns
    @chart = ChartFactory.get_chart params[:select_district], params[:select_crime_type], params[:select_month], params[:select_year]
  end

  def maps
    setup_dropdowns
    create_overlay
  end

private
    def setup_dropdowns
      @district_list = District.order(:name)
      @crime_type_list = CrimeType.order(:name)
      @month_list = (1..12).map {|m| [Date::MONTHNAMES[m], m]}
      @year_list = (Occurrence.minimum(:year)..Occurrence.maximum(:year)).map {|m| [m, m]}
    end

    def create_overlay
      # setting filter with the params
      filter = Occurrence.map_filter params[:select_year], params[:select_month], params[:select_crime_type]        

      # Create kml and save to a tmp file
      text = KmlBuilder.build filter, params
      file_name = Rails.root.join("kml_tmp").join("year_#{params[:select_year]}_month_#{params[:select_month]}_crime_type_#{params[:select_crime_type]}").to_s
      save_kml text, file_name

      # zip kml and rename to kmz
      zip_kml file_name

      #upload file
      upload_file("#{file_name}.kmz")
      @kmz_url = get_remote_url("#{file_name}.kmz")
    end 
end

app/views/occurrences/charts.html.haml
%h1= "#{@chart.title}"

= form_tag occurrences_charts_path, method: :get do 
  = label :occurrence, :district, 'Filtro'

  = select_tag :select_district, options_from_collection_for_select(@district_list, 'id', 'name', params[:select_district]), include_blank: "Todos"
  = select_tag :select_crime_type, options_from_collection_for_select(@crime_type_list, 'id', 'name', params[:select_crime_type]), include_blank: "Todos"
  = select_tag :select_month, options_for_select(@month_list, params[:select_month]), include_blank: "Todos"
  = select_tag :select_year, options_for_select(@year_list, params[:select_year]), include_blank: "Todos"

  = submit_tag 'Filtrar', :style => "margin-bottom: 15px;", :class => 'btn btn-primary btn-sm'  
#chart
  <!-- Verificar o tipo da estatisticas e renderizar o gráfico certo -->
  - case @chart.type
  - when :bar
    = bar_chart @chart.data, height: "100%", stacked: true
  - when :column
    = column_chart @chart.data, height: "100%"
  -when :pie
    = pie_chart @chart.data, height: "100%"
  - when :line
    = line_chart @chart.data, discrete: true, label: "Occurrences", height: "100%"
    

app/views/occurrences/maps.html.haml
%h1 Mapa com as Ocorrências
= form_tag occurrences_maps_path, method: :get do 
  = label :occurrence, :district, 'Filtro'

  = select_tag :select_crime_type, options_from_collection_for_select(@crime_type_list, 'id', 'name', params[:select_crime_type]), include_blank: "Todos"
  = select_tag :select_month, options_for_select(@month_list, params[:select_month]), include_blank: "Todos"
  = select_tag :select_year, options_for_select(@year_list, params[:select_year]), include_blank: "Todos"

  = submit_tag 'Filtrar', :class => 'btn btn-primary btn-sm'  

:css
  html, body {
    height: 100%;
    margin: 0;
  }
  #map {
    height: 100%;
    width: 100%;
  }
%div{id: :map}

:javascript
  /**
   * @fileoverview Sample showing capturing a KML file click
   *   and displaying the contents in a side panel instead of
   *   an InfoWindow
   */
  
  var map;
  var src = '#{@kmz_url}?time={Time.now.getutc}';

  
  /**
   * Initializes the map and calls the function that creates polylines.
   */
  function initialize() {
    map = new google.maps.Map(document.getElementById('map'), {
    });
    loadKmlLayer(src, map);
  }
  
  /**
   * Adds a KMLLayer based on the URL passed. Clicking on a marker
   * results in the balloon content being loaded into the right-hand div.
   * @param {string} src A URL for a KML file.
   */
  function loadKmlLayer(src, map) {
    var kmlLayer = new google.maps.KmlLayer(src, {
      map: map
    });
    google.maps.event.addListener(kmlLayer, 'click', function(event) {
      console.log(event.featureData);
    });
  }

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCOiLDNoyiBSvz1oGQtxIt5aYtp_Baxx7Q&signed_in=true&callback=initialize"}